<div class="live-player-page" data-id="<?=$game['id']?>">
<div class="live-player-bar"><b>🎮 QuizSpace Live</b><span><?=e($player['avatar'])?> <?=e($player['nickname'])?></span><b id="player-score"><?=$player['score']?></b></div>
<main id="player-stage">
  <section id="screen-question" class="player-screen"><div id="question-content" class="live-wait">👀 Ви в грі. Чекаємо, поки ведучий почне.</div></section>
  <section id="screen-feedback" class="player-screen hidden" aria-live="assertive"><div id="feedback-icon" class="status-icon"></div><h2 id="feedback-title">Результат</h2><div id="points-awarded" class="points-pop hidden">+0</div></section>
  <section id="screen-leaderboard" class="player-screen hidden"><h3>Ваше поточне місце: <span id="current-rank">—</span></h3><p>Всього балів: <span id="total-score">0</span></p><div id="mini-leaderboard-list"></div></section>
  <section id="screen-podium" class="player-screen hidden"><h2 class="podium-title">Победители квиза!</h2><div class="podium-wrapper"><div class="podium-step step-2"><div class="podium-player" id="podium-user-2">-</div><div class="podium-pillar">2</div></div><div class="podium-step step-1"><div class="podium-crown">👑</div><div class="podium-player" id="podium-user-1">-</div><div class="podium-pillar">1</div></div><div class="podium-step step-3"><div class="podium-player" id="podium-user-3">-</div><div class="podium-pillar">3</div></div></div><p class="podium-my-score">Ваш результат: <b id="final-score">0</b></p></section>
</main></div>

<script>document.body.classList.add('live-player-mode');
(()=>{
 const root=document.querySelector('.live-player-page'),id=root.dataset.id,api='<?=url('live-player-api')?>/'+id;
 const stage=document.getElementById('player-stage'),questionScreen=document.getElementById('screen-question'),questionContent=document.getElementById('question-content'),feedback=document.getElementById('screen-feedback'),leaderboard=document.getElementById('screen-leaderboard'),podiumScreen=document.getElementById('screen-podium'),scoreEl=document.getElementById('player-score'),feedbackTitle=document.getElementById('feedback-title'),feedbackIcon=document.getElementById('feedback-icon'),pointsEl=document.getElementById('points-awarded');
 let current=-1,answered=false,flowLock=false,finished=false,lastScore=Number(scoreEl.textContent||0),feedbackTimer=null;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const shapeNames=['circle','square','triangle','diamond','hexagon','star'],shapeGlyphs=['●','■','▲','◆','⬡','★'],palette=['red','blue','green','purple','orange','teal'];
 function visual(a,qid,i=0){let x=(Number(i)+Number(qid||0))%shapeNames.length;return {shape:shapeNames[x],glyph:shapeGlyphs[x],color:palette[Number(i)%palette.length]}}
 function showOnly(el){[questionScreen,feedback,leaderboard,podiumScreen].forEach(x=>x.classList.add('hidden'));el.classList.remove('hidden')}
 function updateScore(score){lastScore=Number(score)||0;scoreEl.textContent=lastScore}
 function answerButtons(q){return q.answers.map((a,i)=>{let v=visual(a,q.id,i);return `<button type="button" class="live-visual-answer live-color-${v.color} live-shape-${v.shape}" data-a="${a.id}"><span class="live-shape-glyph">${v.glyph}</span><b class="live-answer-text">${esc(a.answer_text)}</b></button>`}).join('')}
 function renderQuestion(q,remaining){showOnly(questionScreen);questionContent.innerHTML=`<div class="player-question live-full-question"><div class="live-q-count">ПИТАННЯ ${q.number} / ${window.__liveTotal||''}</div><h1>${esc(q.prompt)}</h1>${q.image_url?`<img class="live-question-image" src="${esc(q.image_url)}">`:''}<div class="player-answers live-visual-grid">${answerButtons(q)}</div><div class="player-timer">${Math.ceil(remaining)} с</div></div>`;questionScreen.querySelectorAll('.live-visual-answer').forEach(b=>b.onclick=()=>answer(b.dataset.a))}
 function renderLeaderboard(rank,total,ranking){document.getElementById('current-rank').textContent=rank??'—';document.getElementById('total-score').textContent=total??lastScore;const list=document.getElementById('mini-leaderboard-list');list.innerHTML=(ranking||[]).map((p,i)=>`<div class="mini-rank-row ${Number(p.score)===Number(lastScore)?'me':''}"><b>#${i+1}</b><span>${esc(p.avatar||'')} ${esc(p.nickname)}</span><strong>${Number(p.score)}</strong></div>`).join('');showOnly(leaderboard)}
 function renderPodium(players,score){const top=(players||[]).slice().sort((a,b)=>Number(b.score)-Number(a.score)).slice(0,3);document.getElementById('podium-user-1').textContent=top[0]?.nickname||'-';document.getElementById('podium-user-2').textContent=top[1]?.nickname||'-';document.getElementById('podium-user-3').textContent=top[2]?.nickname||'-';document.getElementById('final-score').textContent=Number(score||lastScore);showOnly(podiumScreen);}
 function handlePlayerAnswerResponse(isCorrect,pointsAdded,rank,totalScore,ranking){updateScore(totalScore);feedbackIcon.textContent=isCorrect?'✓':'✕';feedbackTitle.textContent=isCorrect?'Правильно!':'Неправильно!';pointsEl.classList.add('hidden');pointsEl.textContent=`+${Number(pointsAdded)||0}`;void pointsEl.offsetWidth;if(isCorrect&&Number(pointsAdded)>0)pointsEl.classList.remove('hidden');showOnly(feedback);clearTimeout(feedbackTimer);feedbackTimer=setTimeout(()=>{renderLeaderboard(rank,totalScore,ranking);flowLock=false},1800)}
 async function poll(){try{const r=await fetch(api,{credentials:'same-origin'}),d=await r.json();window.__liveTotal=d.total||window.__liveTotal;if(d.status==='finished'){finished=true;flowLock=false;updateScore(d.score);renderPodium(d.players,d.score);return}if(finished)return;if(flowLock)return;if(d.status==='lobby'){showOnly(questionScreen);questionContent.innerHTML='<div class="live-wait live-wait-full">👀 Чекаємо початку гри…</div>';return}if(!d.question)return;if(current!==d.question.id){current=d.question.id;answered=!!d.answered;renderQuestion(d.question,d.remaining);if(answered)questionScreen.querySelectorAll('.live-visual-answer').forEach(b=>b.disabled=true)}else{const t=questionScreen.querySelector('.player-timer');if(t)t.textContent=Math.ceil(d.remaining)+' с';if(d.answered)questionScreen.querySelectorAll('.live-visual-answer').forEach(b=>b.disabled=true)}}catch(e){}}
 async function answer(a){if(answered||flowLock||finished)return;answered=true;flowLock=true;questionScreen.querySelectorAll('.live-visual-answer').forEach(b=>b.disabled=true);const fd=new FormData();fd.append('csrf','<?=csrf()?>');fd.append('answer_id',a);try{const r=await fetch(api,{method:'POST',body:fd,credentials:'same-origin'}),d=await r.json();if(d.ok){handlePlayerAnswerResponse(!!d.correct,Number(d.points||0),Number(d.rank||1),Number(d.score||0),d.ranking||[])}}catch(e){flowLock=false}}
 poll();setInterval(poll,500);
})();</script>
