<?php $editing=!empty($roulette); ?>
<div class="page-head"><div><a class="back" href="<?=url('course/'.$courseId)?>">← Курс</a><span class="eyebrow">ІНТЕРАКТИВ</span><h1><?=$editing?'Редагувати рулетку':'Створити рулетку'?></h1><p class="muted">Кожен сектор може мати свій текст, картинку та вагу випадання.</p></div></div>
<form method="post" enctype="multipart/form-data" class="stack" id="roulette-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><div class="card form"><label>Назва<input name="title" required value="<?=e($roulette['title']??'')?>"></label><label>Опис<textarea name="description"><?=e($roulette['description']??'')?></textarea></label></div>
<div class="matching-builder-head"><div><h2>Сектори</h2><p class="muted">Наприклад: «Питання 1», «Бонус», «Повторити».</p></div><button type="button" class="btn ghost" id="add-segment">＋ Додати сектор</button></div><div id="segments" class="stack"></div>
<div class="actions"><a class="btn ghost" href="<?=url('course/'.$courseId)?>">Скасувати</a><button class="btn primary">💾 <?=$editing?'Зберегти':'Створити'?></button></div></form>
<script>
(()=>{let i=0;const root=document.getElementById('segments');const existing=<?=json_encode($segments??[],JSON_UNESCAPED_UNICODE|JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT)?>;
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function add(d=null){const n=i++,el=document.createElement('div');el.className='card roulette-segment-editor';el.dataset.segment='';el.innerHTML=`<div class="section-title"><h3>Сектор ${n+1}</h3><button type="button" class="btn danger" data-remove>🗑</button></div><input type="hidden" name="segment_id[${n}]" value="${d?.id||0}"><div class="grid2"><label>Текст<input name="label[${n}]" required value="${esc(d?.label)}"></label><label>Вага<input type="number" min="0.01" step="0.01" name="weight[${n}]" value="${d?.weight||1}"></label></div><label>Картинка сектора<input type="file" name="segment_image_${n}" accept="image/*"></label>${d?.image_path?`<img class="editor-image small" src="<?=base_url()?>/${esc(d.image_path)}">`:''}`;root.appendChild(el);el.animate([{opacity:0,transform:'translateY(10px)'},{opacity:1,transform:'none'}],{duration:220});}
function ren(){[...root.children].forEach((x,n)=>x.querySelector('h3').textContent='Сектор '+(n+1));}root.addEventListener('click',e=>{if(e.target.closest('[data-remove]')){const x=e.target.closest('[data-segment]');if(root.children.length<=2)return;x.classList.add('pair-removing');setTimeout(()=>{x.remove();ren()},180)}});document.getElementById('add-segment').onclick=()=>add();if(existing.length)existing.forEach(add);else{add();add();add();add();}
})();</script>