<?php $editing=!empty($editId); $oldCards=$existingCards??[]; ?>
<div class="qs-game-shell"><div class="section-title"><div><span class="eyebrow">КВИЗ С КАРТОЧКАМИ</span><h1><?=$editing?'Редактирование':'Новый квиз'?></h1><p class="muted">Сделайте один именованный квиз и добавляйте карточки.</p></div><a class="btn ghost" href="<?=url('course/'.$courseId)?>">← Назад</a></div>
<form method="post" enctype="multipart/form-data" class="qs-game-builder"><input type="hidden" name="csrf" value="<?=csrf()?>"><div class="card"><label>Название квиза<input name="title" required value="<?=e($quiz['title']??'')?>" placeholder="Animals Vocabulary"></label></div><div class="card fc-import-card"><label>Быстро добавить карточки из текста<p class="muted" style="margin:4px 0 8px">Каждая строка: <b>лицо - обратная сторона</b></p><textarea id="fcImportText" rows="5" placeholder="cat - кіт
dog - собака
book - книга"></textarea></label><button type="button" class="btn ghost" id="importFcText">＋ Превратить текст в карточки</button></div><div id="fcItems"></div><div class="actions"><button type="button" class="btn ghost" id="addFc">＋ Добавить карточку</button><button class="btn primary"><?=$editing?'Сохранить изменения':'Создать квиз'?></button></div></form></div>
<script>
(()=>{const box=document.getElementById('fcItems');let key=0;const existing=<?=json_encode(array_values($oldCards),JSON_UNESCAPED_UNICODE)?>;
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;')}
function add(data=null){const k=key++,n=box.children.length+1,d=document.createElement('div');d.className='card fc-item';d.dataset.key=k;d.innerHTML=`<div class="item-head"><b>#${n}</b><button type="button" class="btn danger remove-row">🗑</button></div><input type="hidden" name="card_key[]" value="${k}"><input type="hidden" name="existing_front_image[]" value="${esc(data?.front_image_path)}"><input type="hidden" name="existing_back_image[]" value="${esc(data?.back_image_path)}"><input type="hidden" name="existing_front_audio[]" value="${esc(data?.front_audio_path)}"><input type="hidden" name="existing_back_audio[]" value="${esc(data?.back_audio_path)}"><div class="grid2"><div><label>Лицевая сторона<textarea name="front[]" required>${esc(data?.front_text)}</textarea></label><label>Изображение<input type="file" name="front_image_${k}" accept="image/*"></label><label>Аудиофайл<input type="file" name="front_audio_${k}" accept="audio/*"></label><label>Аудио URL<input name="front_audio_url[]" value="${esc(data?.front_audio_path)}" placeholder="https://.../audio.mp3"></label></div><div><label>Задняя сторона<textarea name="back[]" required>${esc(data?.back_text)}</textarea></label><label>Изображение<input type="file" name="back_image_${k}" accept="image/*"></label><label>Аудиофайл<input type="file" name="back_audio_${k}" accept="audio/*"></label><label>Аудио URL<input name="back_audio_url[]" value="${esc(data?.back_audio_path)}" placeholder="https://.../audio.mp3"></label></div></div><div class="fc-tts-row"><button type="button" class="btn ghost tts-front">🔊 Озвучить лицевую</button><button type="button" class="btn ghost tts-back">🔊 Озвучить обратную</button></div>`;box.appendChild(d);ren()}
function ren(){box.querySelectorAll('.fc-item').forEach((x,i)=>x.querySelector('.item-head b').textContent='#'+(i+1))}
document.getElementById('addFc').addEventListener('click',()=>add());
document.getElementById('importFcText').addEventListener('click',()=>{
 const area=document.getElementById('fcImportText');
 const lines=area.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);let added=0;
 lines.forEach(line=>{const m=line.match(/^(.*?)\s+-\s+(.*)$/);if(!m)return;add({front_text:m[1].trim(),back_text:m[2].trim()});added++;});
 if(added){area.value='';area.focus();}
 else if(lines.length) alert('Не найден формат «лицо - обратная сторона».');
});
box.addEventListener('click',e=>{const row=e.target.closest('.fc-item');if(!row)return;if(e.target.closest('.remove-row')){if(box.children.length<=2){alert('Минимум 2 карточки.');return;}row.remove();ren()}if(e.target.closest('.tts-front')){const t=row.querySelector('textarea[name="front[]"]')?.value||'';if(t&&speechSynthesis){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t))}}if(e.target.closest('.tts-back')){const t=row.querySelector('textarea[name="back[]"]')?.value||'';if(t&&speechSynthesis){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t))}}});
if(existing.length) existing.forEach(x=>add(x)); else {add();add();}
})();
</script>